<div class="flex flex-col gap-6" @if($explorationId) wire:poll.3s @endif>
    <div><p class="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Catalog explorer</p><h1 class="mt-2 text-3xl font-semibold text-white">Dentro una label.</h1></div>
    <form wire:submit="explore" class="panel grid gap-4 p-5 md:grid-cols-6"><div class="md:col-span-2"><label class="label">Nome, ID o URL Discogs</label><input wire:model="label" class="field" placeholder="Crisp Recordings"></div><div><label class="label">Anno da</label><input wire:model="yearFrom" type="number" class="field"></div><div><label class="label">Anno a</label><input wire:model="yearTo" type="number" class="field"></div><div><label class="label">Formato</label><input wire:model="format" class="field" placeholder="Vinyl"></div><div><label class="label">Stili</label><input wire:model="styles" class="field" placeholder="Deep House"></div><div class="flex items-center gap-4 md:col-span-3"><label class="text-sm text-zinc-400"><input wire:model="hideSeen" type="checkbox" class="accent-amber-300"> Nascondi viste</label><label class="text-sm text-zinc-400"><input wire:model="fresh" type="checkbox" class="accent-amber-300"> Ignora cache</label></div><div class="flex gap-2 md:col-span-3 md:justify-end"><button class="btn-primary">Esplora</button>@if($catalog)<button type="button" wire:click="export" class="btn-secondary">CSV</button>@endif</div>@error('*')<p class="text-sm text-red-300 md:col-span-full">{{ $message }}</p>@enderror</form>
    @if($error)<div class="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{{ $error }}</div>@endif
    @if($details)
        <section class="grid gap-4 lg:grid-cols-[1fr_340px]"><div class="panel p-6"><span class="badge">Discogs #{{ $details['id'] }}</span><h2 class="mt-4 text-3xl font-semibold text-white">{{ $details['name'] }}</h2><div class="mt-5 flex flex-wrap gap-2">@foreach($details['top_styles'] as $style => $count)<span class="badge">{{ $style }} · {{ $count }}</span>@endforeach</div><div class="mt-6 grid gap-4 border-t border-white/8 pt-5 sm:grid-cols-2"><div><span class="label">Label madre</span>{{ $details['parent']['name'] ?? '—' }}</div><div><span class="label">Sub-label</span>{{ collect($details['sublabels'])->pluck('name')->implode(', ') ?: '—' }}</div></div></div><aside class="panel p-6"><span class="label">Connessioni</span><p class="text-sm leading-6 text-zinc-400">Trova etichette collegate attraverso artisti condivisi. L'analisi gira in coda.</p><button wire:click="startSiblingSearch" class="btn-secondary mt-4 w-full">Trova label sorelle</button>@if($exploration)<div class="mt-5"><div class="mb-2 flex justify-between text-xs text-zinc-500"><span>{{ $exploration->message }}</span><span>{{ $exploration->progress }}%</span></div><div class="h-1.5 overflow-hidden rounded-full bg-white/5"><div class="h-full bg-amber-300 transition-all" style="width: {{ $exploration->progress }}%"></div></div>@if($exploration->status === 'completed')<div class="mt-4 flex flex-col gap-2">@foreach($exploration->results ?? [] as $sibling)<div class="flex justify-between text-sm"><span>{{ $sibling['name'] }}</span><span class="text-zinc-500">{{ $sibling['shared_artists'] }}</span></div>@endforeach</div>@endif</div>@endif</aside></section>
        <section class="panel overflow-hidden"><div class="border-b border-white/8 px-5 py-4"><strong>{{ count($catalog) }} release nel catalogo</strong></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Release</th><th>Label / stile</th><th>Anno</th><th>Have</th><th>Want</th><th>Ratio</th><th>Azioni</th></tr></thead><tbody>@foreach($catalog as $release)<tr wire:key="catalog-{{ $release['id'] }}"><td><a href="{{ $release['url'] }}" target="_blank" rel="noopener" class="font-medium text-amber-200 hover:underline">{{ $release['artist'] }} — {{ $release['title'] }}</a><div class="mt-1 text-xs text-zinc-600">{{ $release['catalog_number'] ?: '—' }}</div></td><td>{{ implode(', ', $release['labels']) }}<div class="mt-1 text-xs text-zinc-500">{{ implode(', ', $release['styles']) }}</div></td><td>{{ $release['year'] ?: '—' }}</td><td>{{ $release['have'] }}</td><td>{{ $release['want'] }}</td><td class="text-cyan-300">{{ number_format($release['want_ratio'], 2) }}</td><td><div class="flex gap-2"><button wire:click="markSeen({{ $release['id'] }})" class="text-xs text-zinc-400">Vista</button><button wire:click="loadVideos({{ $release['id'] }})" class="text-xs text-zinc-400">Video</button></div>@if(array_key_exists($release['id'], $videos))@forelse($videos[$release['id']] as $video)<a href="{{ $video }}" target="_blank" rel="noopener" class="mt-2 block text-xs text-red-300">YouTube ↗</a>@empty<span class="mt-2 block text-xs text-zinc-600">Nessun video</span>@endforelse@endif</td></tr>@endforeach</tbody></table></div></section>
    @endif
</div>
