<div class="flex flex-col gap-6">
    <div><p class="text-xs font-semibold uppercase tracking-[.2em] text-amber-300">Label radar</p><h1 class="mt-2 text-3xl font-semibold text-white">Etichette piccole. Identità forte.</h1><p class="mt-2 text-zinc-500">Classifica le label per specializzazione nello stile.</p></div>
    <form wire:submit="search" class="panel grid gap-4 p-5 md:grid-cols-4">
        <div class="md:col-span-2"><label class="label">Stile principale</label><input wire:model="style" class="field" placeholder="Deep House"></div><div class="md:col-span-2"><label class="label">Nome label <span class="normal-case tracking-normal">(anche parziale)</span></label><input wire:model="labelName" class="field" placeholder="Crisp Recordings"></div>
        <div class="md:col-span-2"><label class="label">Deve includere <span class="normal-case tracking-normal">(stili separati da virgola)</span></label><input wire:model="also" class="field" placeholder="Dub Techno, Ambient"></div><div class="md:col-span-2"><label class="label">Escludi</label><input wire:model="exclude" class="field" placeholder="Tech House"></div>
        <div><label class="label">Catalogo massimo</label><input wire:model="maxReleases" type="number" class="field" placeholder="500"></div><div><label class="label">Numero label</label><input wire:model="limit" type="number" class="field"></div>
        <label class="flex items-center gap-2 text-sm text-zinc-400"><input wire:model="fresh" type="checkbox" class="accent-amber-300"> Ignora cache</label><div class="flex gap-2 md:justify-end"><button class="btn-primary">Mappa label</button>@if($labels)<button type="button" wire:click="export" class="btn-secondary">CSV</button>@endif</div>
        @error('*')<p class="text-sm text-red-300 md:col-span-full">{{ $message }}</p>@enderror
    </form>
    @if($error)<div class="rounded-xl border border-red-400/25 bg-red-400/10 p-4 text-red-100"><strong class="block">Ricerca non eseguita</strong><span class="mt-1 block text-red-200/80">{{ $error }}</span></div>@endif
    @if($hasSearched && !$error && !$labels)<div class="panel p-8 text-center"><p class="font-medium text-zinc-300">Nessuna label corrisponde ai filtri.</p><p class="mt-2 text-sm text-zinc-500">Il nome è case-insensitive; gli stili in “Deve includere” devono comparire tutti nella stessa release.</p></div>@endif
    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@foreach($labels as $index => $label)<a href="{{ route('label.show', ['label' => $label['name']]) }}" wire:navigate class="panel group p-5 transition hover:-translate-y-0.5 hover:border-amber-300/25"><div class="flex items-start justify-between"><span class="text-xs text-zinc-600">#{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span><span class="badge text-amber-200">{{ number_format($label['specialization'] * 100, 1) }}%</span></div><h2 class="mt-5 text-xl font-semibold text-white group-hover:text-amber-200">{{ $label['name'] }}</h2><div class="mt-5 grid grid-cols-3 gap-3 border-t border-white/8 pt-4 text-sm"><div><span class="label">Release</span>{{ $label['styleReleaseCount'] }}</div><div><span class="label">Ratio</span>{{ number_format($label['averageWantRatio'], 2) }}</div><div><span class="label">Catalogo</span>{{ $label['catalogSize'] }}</div></div></a>@endforeach</div>
</div>
